<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260531130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create asynchronous Intelligence incoming event intake table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE intelligence_incoming_event (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            process_key VARCHAR(255) NOT NULL,
            connector_type VARCHAR(64) NOT NULL,
            connection_name VARCHAR(255) DEFAULT NULL,
            document_id VARCHAR(255) DEFAULT NULL,
            document_uuid VARCHAR(255) DEFAULT NULL,
            event_key VARCHAR(255) DEFAULT NULL,
            external_event_key VARCHAR(255) DEFAULT NULL,
            occurred_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            content_type VARCHAR(255) DEFAULT NULL,
            raw_payload TEXT NOT NULL,
            normalized_payload_json JSONB DEFAULT NULL,
            status VARCHAR(32) NOT NULL,
            retry_count INT NOT NULL,
            last_error TEXT DEFAULT NULL,
            processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_intelligence_incoming_event_status ON intelligence_incoming_event (status)');
        $this->addSql('CREATE INDEX idx_intelligence_incoming_event_process_key ON intelligence_incoming_event (process_key)');
        $this->addSql('CREATE INDEX idx_intelligence_incoming_event_received_at ON intelligence_incoming_event (received_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE intelligence_incoming_event');
    }
}
