<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260529120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create persistent Intelligence event, process instance, and context snapshot tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE intelligence_process_instance (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            source_system VARCHAR(64) NOT NULL,
            process_key VARCHAR(255) NOT NULL,
            template_version VARCHAR(128) NOT NULL,
            document_external_id VARCHAR(255) NOT NULL,
            document_uuid VARCHAR(255) DEFAULT NULL,
            document_identity_key VARCHAR(320) NOT NULL,
            document_version INT NOT NULL,
            status VARCHAR(64) NOT NULL,
            current_step_key VARCHAR(255) NOT NULL,
            started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            last_event_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_intelligence_process_instance_identity ON intelligence_process_instance (source_system, process_key, template_version, document_identity_key, document_version)');
        $this->addSql('CREATE INDEX idx_intelligence_process_instance_process_key ON intelligence_process_instance (process_key)');
        $this->addSql('CREATE INDEX idx_intelligence_process_instance_document_uuid ON intelligence_process_instance (document_uuid)');
        $this->addSql('CREATE INDEX idx_intelligence_process_instance_document_version ON intelligence_process_instance (document_version)');
        $this->addSql('CREATE INDEX idx_intelligence_process_instance_current_step_key ON intelligence_process_instance (current_step_key)');
        $this->addSql('CREATE INDEX idx_intelligence_process_instance_status ON intelligence_process_instance (status)');

        $this->addSql('CREATE TABLE intelligence_process_event (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            process_instance_id INT DEFAULT NULL,
            external_event_key VARCHAR(255) NOT NULL,
            source_system VARCHAR(64) NOT NULL,
            process_key VARCHAR(255) NOT NULL,
            event_key VARCHAR(255) NOT NULL,
            step_key VARCHAR(255) NOT NULL,
            document_external_id VARCHAR(255) NOT NULL,
            document_uuid VARCHAR(255) DEFAULT NULL,
            document_version INT NOT NULL,
            actor_ref VARCHAR(255) DEFAULT NULL,
            occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            raw_event_json JSONB NOT NULL,
            normalized_event_json JSONB NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_intelligence_process_event_external_key ON intelligence_process_event (external_event_key)');
        $this->addSql('CREATE INDEX idx_intelligence_process_event_process_key ON intelligence_process_event (process_key)');
        $this->addSql('CREATE INDEX idx_intelligence_process_event_document_uuid ON intelligence_process_event (document_uuid)');
        $this->addSql('CREATE INDEX idx_intelligence_process_event_document_version ON intelligence_process_event (document_version)');
        $this->addSql('CREATE INDEX idx_intelligence_process_event_process_instance_id ON intelligence_process_event (process_instance_id)');
        $this->addSql('CREATE INDEX idx_intelligence_process_event_occurred_at ON intelligence_process_event (occurred_at)');
        $this->addSql('ALTER TABLE intelligence_process_event ADD CONSTRAINT fk_intelligence_process_event_process_instance FOREIGN KEY (process_instance_id) REFERENCES intelligence_process_instance (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE intelligence_context_snapshot (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            process_instance_id INT DEFAULT NULL,
            source_system VARCHAR(64) NOT NULL,
            document_external_id VARCHAR(255) NOT NULL,
            document_uuid VARCHAR(255) DEFAULT NULL,
            document_version INT NOT NULL,
            process_key VARCHAR(255) DEFAULT NULL,
            external_event_key VARCHAR(255) DEFAULT NULL,
            captured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            context_json JSONB NOT NULL,
            warnings JSONB NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_intelligence_context_snapshot_process_key ON intelligence_context_snapshot (process_key)');
        $this->addSql('CREATE INDEX idx_intelligence_context_snapshot_document_uuid ON intelligence_context_snapshot (document_uuid)');
        $this->addSql('CREATE INDEX idx_intelligence_context_snapshot_document_version ON intelligence_context_snapshot (document_version)');
        $this->addSql('CREATE INDEX idx_intelligence_context_snapshot_process_instance_id ON intelligence_context_snapshot (process_instance_id)');
        $this->addSql('ALTER TABLE intelligence_context_snapshot ADD CONSTRAINT fk_intelligence_context_snapshot_process_instance FOREIGN KEY (process_instance_id) REFERENCES intelligence_process_instance (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE intelligence_context_snapshot DROP CONSTRAINT fk_intelligence_context_snapshot_process_instance');
        $this->addSql('ALTER TABLE intelligence_process_event DROP CONSTRAINT fk_intelligence_process_event_process_instance');
        $this->addSql('DROP TABLE intelligence_context_snapshot');
        $this->addSql('DROP TABLE intelligence_process_event');
        $this->addSql('DROP TABLE intelligence_process_instance');
    }
}
