<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260615120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Intelligence visibility check result table for persisted access/visibility evaluations.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE intelligence_visibility_check_result (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            process_event_id INT DEFAULT NULL,
            process_instance_id INT DEFAULT NULL,
            external_event_key VARCHAR(255) DEFAULT NULL,
            document_uuid VARCHAR(255) NOT NULL,
            document_version INT DEFAULT NULL,
            process_key VARCHAR(255) NOT NULL,
            source_system VARCHAR(64) NOT NULL,
            step_key VARCHAR(255) NOT NULL,
            event_phase VARCHAR(16) NOT NULL,
            check_key VARCHAR(255) NOT NULL,
            profile_key VARCHAR(255) DEFAULT NULL,
            probe_key VARCHAR(255) NOT NULL,
            probe_type VARCHAR(255) DEFAULT NULL,
            probe_ref VARCHAR(255) DEFAULT NULL,
            expected VARCHAR(16) NOT NULL,
            actual VARCHAR(16) NOT NULL,
            status VARCHAR(32) NOT NULL,
            reason VARCHAR(255) DEFAULT NULL,
            checked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            attempt_no INT DEFAULT 1 NOT NULL,
            is_final BOOLEAN DEFAULT true NOT NULL,
            document_count INT DEFAULT NULL,
            raw_result_json JSONB DEFAULT NULL,
            details_json JSONB DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_intelligence_visibility_document_process ON intelligence_visibility_check_result (document_uuid, process_key)');
        $this->addSql('CREATE INDEX idx_intelligence_visibility_process_step_phase ON intelligence_visibility_check_result (process_key, source_system, step_key, event_phase)');
        $this->addSql('CREATE INDEX idx_intelligence_visibility_status_checked ON intelligence_visibility_check_result (status, checked_at)');
        $this->addSql('CREATE INDEX idx_intelligence_visibility_external_check ON intelligence_visibility_check_result (external_event_key, check_key)');
        $this->addSql("COMMENT ON COLUMN intelligence_visibility_check_result.checked_at IS 'UTC timestamp stored without database timezone offset.'");
        $this->addSql("COMMENT ON COLUMN intelligence_visibility_check_result.created_at IS 'UTC timestamp stored without database timezone offset.'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE intelligence_visibility_check_result');
    }
}
