<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260601090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Intelligence process version baseline table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE intelligence_process_version (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            process_key VARCHAR(255) NOT NULL,
            version VARCHAR(128) NOT NULL,
            valid_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            description TEXT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_intelligence_process_version_process_version ON intelligence_process_version (process_key, version)');
        $this->addSql('CREATE INDEX idx_intelligence_process_version_process_valid_from ON intelligence_process_version (process_key, valid_from)');
        $this->addSql("COMMENT ON COLUMN intelligence_process_version.valid_from IS 'UTC timestamp stored without database timezone offset.'");
        $this->addSql("COMMENT ON COLUMN intelligence_process_version.created_at IS 'UTC timestamp stored without database timezone offset.'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE intelligence_process_version');
    }
}
