name: Deploy Staging

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.APRILSTAGINGHOST }}
          username: ${{ secrets.APRILSTAGINGUSER }}
          key: ${{ secrets.APRILSTAGINGSSHKEY }}
          script: |
            /srv/april/deploy.sh
